services:
  - type: web
    name: medrag-backend
    root: medrag-backend
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PIP_EXTRA_INDEX_URL
        value: https://download.pytorch.org/whl/cpu